[build]
  base = "."
  command = "npm run build"
  publish = "build"

[context.production.environment]
  SITE_ID = "1be9ce5e-9787-4b2c-8570-6610579ae3d3"

[functions]
  directory = "netlify/functions"
  