[build]
  base = "."
  command = "npm run build"
  publish = "build"  # Build çıktılarınızın bulunduğu dizin
  
[context.production.environment]
  SITE_ID = "1be9ce5e-9787-4b2c-8570-6610579ae3d3"  # Site ID, doğru görünüyor

[functions]
  directory = "netlify/functions"  # Fonksiyonlar dizini
  external_node_modules = ["express", "ejs"]
  node_bundler = "esbuild"
  included_files = ["views/", "public/"]